spring:
  dubbo:
    application:
      name: provider1
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
  datasource:
    url: jdbc:mysql://localhost:3306/inst01
    username: root
    password: qweasd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
debug: true